// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTO_3wPA4chJ2TpwgFAtoevOU7OENRnTA',
    appId: '1:229220651467:web:9d7816fa0d13b510d1264e',
    messagingSenderId: '229220651467',
    projectId: 'appie-67591',
    authDomain: 'appie-67591.firebaseapp.com',
    storageBucket: 'appie-67591.firebasestorage.app',
    measurementId: 'G-2ZP4TJDCJX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA38wKEYQCFI1C5xgbppBjUN5jZ-2U2ATc',
    appId: '1:229220651467:android:b900fbce94ee51e6d1264e',
    messagingSenderId: '229220651467',
    projectId: 'appie-67591',
    storageBucket: 'appie-67591.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwUXxwoyZRKGS3S-qwSNTOiU4e_oZGsLA',
    appId: '1:229220651467:ios:494c6314c0f784b9d1264e',
    messagingSenderId: '229220651467',
    projectId: 'appie-67591',
    storageBucket: 'appie-67591.firebasestorage.app',
    iosBundleId: 'com.appie.appie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwUXxwoyZRKGS3S-qwSNTOiU4e_oZGsLA',
    appId: '1:229220651467:ios:494c6314c0f784b9d1264e',
    messagingSenderId: '229220651467',
    projectId: 'appie-67591',
    storageBucket: 'appie-67591.firebasestorage.app',
    iosBundleId: 'com.appie.appie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTO_3wPA4chJ2TpwgFAtoevOU7OENRnTA',
    appId: '1:229220651467:web:474f5958cfe2a2dbd1264e',
    messagingSenderId: '229220651467',
    projectId: 'appie-67591',
    authDomain: 'appie-67591.firebaseapp.com',
    storageBucket: 'appie-67591.firebasestorage.app',
    measurementId: 'G-XCWJ80DEVY',
  );
}
